version: '3.7'

services: 
      
  telegraf:
    image: telegraf:1.10
    volumes:
      - ./telegraf/conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  influxdb:
    image: influxdb:1.5.4
    volumes: 
      - ./influxdb/data:/var/lib/influxdb
    ports: 
      - 8086:8086

  chronograf:
    image: chronograf:1.7.8
    volumes:
      - ./chronograf/data:/var/lib/chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports:
      - 8888:8888

  kapacitor:
    image: kapacitor:1.5.2
    volumes:
      - ./kapacitor/data:/var/lib/kapacitor
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    ports:
      - 9092:9092

  # incase you want to use grafana instead of chronograf
  # grafana:
  #   image: grafana/grafana:5.4.3
  #   volumes: 
  #     - ./grafana/data:/var/lib/grafana
  #   ports:
  #     - 3000:3000
